name: corsac_console
version: 0.1.0
description: Framework for console applications
homepage: https://github.com/corsac-dart/console
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=1.12.0 <2.0.0'

dependencies:
  args: "^0.13.3+1"
  logging: "^0.11.2"
  corsac_kernel:
    git: https://github.com/corsac-dart/kernel.git

dev_dependencies:
  test: "^0.12.6+1"
  dart_coveralls: "^0.4.0"
